const int A = 123;
const highp float PI = 3.14159;
const vec3 X_AXIS = vec3(1.0, 0.0, 0.0),
		   Y_AXIS = vec3(0.0, 1.0, 0.0),
		   Z_AXIS = vec3(0.0, 0.0, 1.0);
const float SPEED = 2.0, GRAVITY = 9.81;

void f() {
	const int localA = 123;
	const highp float localPI = 3.14159;
	const vec3 localX_AXIS = vec3(1.0, 0.0, 0.0),
			   localY_AXIS = vec3(0.0, 1.0, 0.0),
			   localZ_AXIS = vec3(0.0, 0.0, 1.0);
	const float localSPEED = 2.0, localGRAVITY = 9.81;
}
