void f() {
	
}

int getInt() {
	return 42;
}

void setValue(float v) {
	
}

vec3 mixColors(vec3 a, vec3 b, float t) {
	return a;
}

void allQualifiers(in int a, out float b, inout vec3 c, const mat4 d, const in vec2 e) {
	
}

void withPrecision(highp float a, mediump int b) {
	
}

float sum(float values[16]) {
	return 0.0;
}

float sum2(float[16] values) {
	return 0.0;
}

highp vec4 complexFunc(inout lowp vec2 p1[4], const sampler2D p2) {

}
