void f() {
	if (true) {
		
	}
	
	if (true) {
		
	}
	else {
		
	}
	
	if (true) {
		
	}
	else if (true) {
		
	}
	else {
		
	}
	
	if (true) {
		if (true) {
			
		}
		else if (true) {
			
		}
		else {
			
		}
	}
	else {
		if (true) {
			
		}
		else if (true) {
			
		}
		else {
			
		}
	}
	
	if (true);
	else;
	
	if (true);
	else if (true);
	else;
	
	if (true)
		if (true);
		else if (true);
		else;
	else 
		if (true);
		else if (true);
		else;
}
